# Generated by Django 4.2.11 on 2024-06-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="url",
            field=models.TextField(default="", unique=True),
        ),
    ]
