# Generated by Django 5.1.3 on 2026-02-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_alter_site_ping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="ping",
            field=models.DecimalField(
                blank=True, decimal_places=2, default="", max_digits=7, null=True
            ),
        ),
    ]
