# Generated by Django 4.2.11 on 2024-06-02 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_alter_site_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="site",
            name="slug",
        ),
    ]
