# Generated by Django 4.2.11 on 2024-06-13 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_remove_site_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="subscribed",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="unsubscribed",
        ),
    ]
